/*CREAMOS LA BASE DE DATOS LLAMAREMOS CONEXION1*/
create database conexion1;
/*HACEMOS USO DE LA BASE DE DATOS*/
use conexion1;
/*ACTULIZAMOS SCHEMAS PARA VER LA BASE DE DATOS CREADA EN LA PARTE IZQUIERDA
DE CONTENIDOS DE LAS BASES CREADAS*/
/*CREAMOS UNA TABLA QUE LLAMAREMOS ALUMNOS*/
create table alumnos(codigo int(11) primary key, nombres varchar(50), correo varchar(40),
codigocurso int(6));
/*REVISAMOS LA ESTRUCTURA DE LA TABLA ALUMNOS PARA ESTAR SEGUROS DE QUE HA
QUEDADO BIEN*/
describe alumnos;
/*ABRIMOS EL PROGRAMA HECHO EN HTML PARA EL CASO PAGINA.HTML CORREMOS LA
PAGINA Y HACEMOS LA CARGA DE 2 REGISTROS */
select * from alumnos;